### ISSUE TITLE
homework review completed, 請調整

### ISSUE THREAD

**Issue by hatelove** [bird1217/TDD_Day1#1]
以下幾點建議：
1. 測試案例那11筆資料，上課一直強調，沒有循序關係，不要用 for loop 去長，他們只是剛好看起來好像有循序關係而已。所以請你把用 loop 長測試資料的習慣改掉。
2. 把 GroupColumnCalculate() 所需要的資訊透過 constructor 初始化，有好處也有壞處，在這個需求場景可能壞處居多。如果針對這 11 筆 Product 資料，我需要 3 筆一組取得 Cost 總和，也需要 3 筆一組取得 revenue 的總和，目前這樣的API設計底下，只能重 new GroupCalculate(), 否則無法滿足需求。這類使用場景，建議用參數來決定會好一些。

**Comment by bird1217** [comment]
麻煩91哥  review程式 ,

已針對建議做了調整.

**Comment by hatelove** [comment]
第一個 scenario 是針對 Cost, 不是 Id 唷

**Comment by bird1217** [comment]
抱歉...沒看清楚題目!

已經修正程式 , 將群組計算欄位改為Cost

**Comment by hatelove** [comment]
homework 的部分已經OK了，production code 的實作方式，參考一下我的 sample solution 在測試案例跟 production code 設計上的差異：http://bit.ly/91-tdd-day1-homework-solution
